import replace from "@rollup/plugin-replace";

function getEnvVariables() {
  // Fail at build time if missing!
  if (!process.env.CI && !process.env.SUBGRAPH_API_KEY) {
    throw new Error(
      "SUBGRAPH_API_KEY is not set in the environment variables.",
    );
  }
  return {
    preventAssignment: true,
    values: {
      // the double string generated by JSON.stringify is required by the plugin
      "process.env.SUBGRAPH_API_KEY": JSON.stringify(
        process.env.SUBGRAPH_API_KEY,
      ),
    },
  };
}

export default {
  input: "src/index.js",
  output: {
    file: "out.js",
    format: "esm",
    generatedCode: "es2015",
    preserveModules: false,
  },
  plugins: [
    // Env vars should be defined in constants.js,
    // where they will be replaced at build time.
    replace(getEnvVariables()),
  ],
  // Not ideal, but the build may remove functions that are declared but not used.
  // However, Google App Scripts uses the declarations as entry points. With Treeshake enabled,
  // the declarations would be removed.
  treeshake: false,
};
